FROM golang:1.13-alpine AS builder
WORKDIR /go/src/github.com/mrzacarias/dinler
COPY ./ ./
RUN CGO_ENABLED=0 go build -installsuffix 'static' -o /service2 ./cmd/service2

FROM alpine AS final
COPY --from=builder /service2 /service2
